[tool.poetry]
name = "diplomawork-va"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
psycopg2-binary = "^2.9.10"
django = "^5.1.7"
redis = "^5.2.1"
django-filter = "^25.1"
djangorestframework = "^3.15.2"
djangorestframework-simplejwt = "^5.5.0"
drf-yasg = "^1.21.10"
stripe = "^11.6.0"
celery = "^5.4.0"
django-celery-beat = "^2.7.0"
pytest = "^8.3.5"
pillow = "^11.1.0"
django-cors-headers = "^4.7.0"
coverage = "^7.6.12"
docker = "^7.1.0"
pytest-cov = "^6.0.0"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.1.2"
black = "^25.1.0"
isort = "^6.0.1"
mypy = "^1.15.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.0.0"
pytest-django = "^4.10.0"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"
