# Generated by Django 5.1.7 on 2025-03-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="image",
        ),
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
    ]
